### ISSUE TITLE
explain "Isolated tests not supported in this environment. The tests will be run on the main process"

### ISSUE THREAD

**Issue by simsong** [exoticlibraries/libcester#15]
I've added cester to a system and I'm getting this warning, which is perplexing:
```
./cester.h:3277:17: warning: Isolated tests not supported in this environment. The tests will be run on the main process [-W#pragma-messages]
        #pragma message("Isolated tests not supported in this environment. The tests will be run on the main process")
                ^
1 warning generated.
```
It still works, but I'd like to know what the warning means. It's not in the documentation.

**Comment by Thecarisma** [comment]
For each test case cester spawn a subprocess on the platform so if the test case crashed it will not impact the other test cases and as much information about the test case crash can be reported. 

The subprocess is only possible on Windows and Unix based platforms which means your current platform is not Windows, Linux, or Unix variant. On such a platform if a test case crashes the signal.h library will be used to recover and report the crash.

So there is no big impact from the warning just that all the test cases will be executed in one process.

**Comment by simsong** [comment]
My current platform is MacOS, which is (literally) Unix (NeXT had a Unix license). How is the test performed?

**Comment by Thecarisma** [comment]
The check for the Unix system is a simple `#elif defined unix`, with this issue that appears to be unreliable for all Unix platforms. Honestly, I did not test on the MacOS platform, I will do that this week.

For how the test is performed the code block inside each test case is executed. cester just watch the behavior of the test case and the provided assertion macros.

This page https://exoticlibraries.github.io/libcester/how_it_works/index.html provides some information on how this works internally.

**Comment by simsong** [comment]
I found the problem. 
cester uses `#ifdef unix` to determine if it is running on a Unix-like system:
https://github.com/exoticlibraries/libcester/blob/master/include/exotic/cester.h#L3225

However, on MacOS, `#ifdef unix` is not true:

```
% cpp
#ifdef unix
unix is defined!
#endif
# 1 "<stdin>"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 362 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "<stdin>" 2
```

However, `__APPLE__` is defined to be `1`:
```
 % cpp
#ifdef __APPLE__
__APPLE__ is defined!
#endif
# 1 "<stdin>"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 362 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "<stdin>" 2

1 is defined!
```

**Comment by Thecarisma** [comment]
Yes, that is where the check takes place. I have a MacOS set up so I will try to enable the subprocess for MacOS.

**Comment by Thecarisma** [comment]
I've added support for subprocess on MacOS you can download the latest source of cester to get the update, the source code has also been refactored to resolve all the warnings outputed when compiling in C++. 

 I also created a Github action that you can use to install libcester in your CI workflow. 

```yml
    - name: Setup Exotic Libraries
        uses: exoticlibraries/exotic-action@master
        with:
          run-cester-regression: false
```

The snippet above in your workflow yml file will install cester in the include folder. so you don't have to commit cester.h in your repo.

**Comment by simsong** [comment]
Neat. I need to look over the tutorial again, though, as I seem to be having some issues on how I'm including non-test code in my test program.  I'll need to review the tutorial

Thanks again.

**Comment by Thecarisma** [comment]
You can use the CESTER_BODY macro to wrap non-test code. 

```c

#include "cester.h"

CESTER_BODY(
// the logics here

char *platform = "win32";

int compare() {
    return 0;
}

)

// the test cases

```

If you need help along the way don't hesitate to message me

**Comment by simsong** [comment]
Ah! That is not clear. 
Can you point me at a description of how to do something like pytest-style fixtures?

**Comment by Thecarisma** [comment]
the project uses the following macro to setup and cleanup objects

```c
CESTER_BEFORE_ALL
CESTER_BEFORE_EACH
CESTER_AFTER_EACH
CESTER_AFTER_ALL
```

See the description here https://exoticlibraries.github.io/libcester/docs/macros.html?highlight=before#cester-before-all

**Comment by simsong** [comment]
> You can use the CESTER_BODY macro to wrap non-test code.
> 
> ```c
> #include "cester.h"
> 
> CESTER_BODY(
> // the logics here
> 
> char *platform = "win32";
> 
> int compare() {
>     return 0;
> }
> 
> )
> 
> // the test cases
> ```
> 
> If you need help along the way don't hesitate to message me

Hm. That's not working, as I need to do an `#include` inside the block.

**Comment by simsong** [comment]
> > You can use the CESTER_BODY macro to wrap non-test code.
> > ```c
> > #include "cester.h"
> > 
> > CESTER_BODY(
> > // the logics here
> > 
> > char *platform = "win32";
> > 
> > int compare() {
> >     return 0;
> > }
> > 
> > )
> > 
> > // the test cases
> > ```
> > 
> > 
> > If you need help along the way don't hesitate to message me
> 
> Hm. That's not working, as I need to do an `#include` inside the block.

I guess all my `#includes` should themselves have GUARD_BLOCKS to protect against multiple includes...

**Comment by Thecarisma** [comment]
I ll be closing this issue, if you still need more detail on other functionalities please open another issue.
