### ISSUE TITLE
configure libcester repo to properly handle newlines

### ISSUE THREAD

**Issue by simsong** [exoticlibraries/libcester#16]
cester.h appears to have `\r\n` at the end of each line. 

Normally, source code in git has just `\n` at the end, and git automatically transforms these to `\r\n` pairs if a checkout is done on Windows and transforms them back to `\r\n` when the commit is done.

```bash
 % curl -s https://raw.githubusercontent.com/exoticlibraries/libcester/master/include/exotic/cester.h | cat -v |head
^M
/**^M
    \copyright MIT License Copyright (c) 2020, Adewale Azeez ^M
    \author Adewale Azeez <azeezadewale98@gmail.com>^M
    \date 10 April 2020^M
    \file cester.h^M
^M
    Cester is a header only unit testing framework for C. The header ^M
    file can be downloaded and placed in a project folder or can be ^M
    used as part of libopen library by including it in the projects ^M
%
```

This is generally considered incorrect.

For example, when I updated my cester.h to the new version, I got this warning:
```
 % git commit -m 'now follows CESTER specs' -a
warning: CRLF will be replaced by LF in src/tests/cester.h.
The file will have its original line endings in your working directory
[slg-dev fbfbd8a] now follows CESTER specs
 3 files changed, 69 insertions(+), 79 deletions(-)
 create mode 100644 src/tests/Makefile
%
```

You may wish to review these articles and update it accordingly:
* https://docs.github.com/en/github/using-git/configuring-git-to-handle-line-endings
* https://stackoverflow.com/questions/10418975/how-to-change-line-ending-settings
* https://www.edwardthomson.com/blog/git_for_windows_line_endings.html

**Comment by Thecarisma** [comment]
Thanks for bringing that up it never occurs to me I am committing the code with `\r\n` line ending, I save most of my source files with `\n` line endings. 

I will fix that today.

**Comment by Thecarisma** [comment]
The line endings have been fixed in the commit https://github.com/exoticlibraries/libcester/commit/4bf37cd49dd9ae500a96d31fb90b40879b14a1d4

```bash
$ curl -s https://raw.githubusercontent.com/exoticlibraries/libcester/master/include/exotic/cester.h | cat -v |head

/**
    \copyright MIT License Copyright (c) 2020, Adewale Azeez
    \author Adewale Azeez <azeezadewale98@gmail.com>
    \date 10 April 2020
    \file cester.h

    Cester is a header only unit testing framework for C. The header
    file can be downloaded and placed in a project folder or can be
    used as part of libopen library by including it in the projects

```

**Comment by simsong** [comment]
Glad I could help.
