### ISSUE TITLE
Malformed output JUnit xml file

### ISSUE THREAD

**Issue by Kajtek** [exoticlibraries/libcester#17]
From master branch.

Command `./tests --cester-verbose --cester-minimal --cester-output=junitxml > out.xml` produces
```xml
[0m<?xml version="1.0" encoding="UTF-8" ?>
[0m[0m<testsuite tests="[0m[0m1[0m[0m" failures="[0m[0m0[0m[0m" name="[0m[0mtests[0m[0m" errors="0" skipped="[0m[0m0[0m[0m" time="[0m[0m0.00[0m[0m">
[0m[0m    <testcase classname="[0m[0mtests[0m[0m" name="[0m[0mtest_add_should_sum[0m[0m" time="[0m[0m0.00[0m[0m"[0m[0m/>
[0m[0m</testsuite>
[0m
```

Output on terminal looks good.

**Comment by Thecarisma** [comment]
This is due to the color bytes been written into the `out.xml` file. Just add the flag `--cester-nocolor` to disable the coloring.

```bash
./tests --cester-verbose --cester-minimal --cester-output=junitxml --cester-nocolor > out.xml
```

See the doc for more detail and alternative
- https://exoticlibraries.github.io/libcester/docs/options.html#cester-nocolor
- https://exoticlibraries.github.io/libcester/docs/macros.html#cester-nocolor

**Comment by Kajtek** [comment]
@Thecarisma Of course! Thank you for quick response. I was seeking for something like that, do not know why omitted this thing. 

I think it would be also useful to mention it in each output format (I see it is in text, but I didn't even look there) sections like 

[https://exoticlibraries.github.io/libcester/docs/output_formats.html#junitxml](https://exoticlibraries.github.io/libcester/docs/output_formats.html#junitxml)

**Comment by Thecarisma** [comment]
A warning has been added to the top of the output format page to address the issue and its solution.

https://exoticlibraries.github.io/libcester/docs/output_formats.html
