### ISSUE TITLE
File globals

### ISSUE THREAD

**Issue by MarcelInTO** [exoticlibraries/libcester#49]
In the file that contains my tests, I would like to define a structure that holds all of my test configurations and is then used to initialize the arg pointer in CESTER_BEFORE_ALL. So, something like this:

```
struct MyTestSetup
{
   ...
};

CESTER_BEFORE_ALL(inst,
    class MyTestSetup setup;
    inst->arg = &setup;
)
```

However, because the mechanism include the file multiple times, I can't do this because it will fail compilation. I also cannot put the structure definition into the CESTER_BEFORE_ALL definition because then the individual tests won't see it.

So, I can make it work by doing

```
#ifndef DO_ONCE
#define DO_ONCE
struct MyTestSetup
{
   ...
};
#endif

```

Not horrible, but not pretty.

Is there a macro that I did not see that allows me to do this more cleanly?

If not, its not a high priority but I would suggest that there be a CESTER_FILE_GLOBAL() section, or something that does the equivalent of the DO_ONCE hack and allows you to put file global type definitions and variables.

**Comment by Thecarisma** [comment]
The macro [CESTER_BODY](
https://exoticlibraries.github.io/libcester/docs/macros.html#cester-body)
allows you to define global variables.
So you can write your code like

```c
CESTER_BODY(

struct MyTestSetup
{
   ...
};

)


CESTER_BEFORE_ALL(inst,
    class MyTestSetup setup;
    inst->arg = &setup;
)

```

You can check out the other macros at
https://exoticlibraries.github.io/libcester/docs/macros.html and
https://exoticlibraries.github.io/libcester/docs/assertions.html

**Comment by MarcelInTO** [comment]
Perfect! I missed that. Thanks.
