### ISSUE TITLE
Cannot use automatic variables in CESTER_BEFORE_ALL

### ISSUE THREAD

**Issue by MarcelInTO** [exoticlibraries/libcester#50]
I used something like  this:

```
CESTER_BEFORE_ALL(inst,  
    std::vector setup;
    inst->arg = & setup;
)
```

This did not work because the destructor for 'setup' was called before any of the tests were actually called.

This should be a big Warning in the documentation for CESTER_BEFORE_ALL. I know the example uses dynamic allocation which gets around the problem, but it does not explain why. I think it needs a clear statement that you must use data that is not automatically deallocated.

In hindsight I understand why this is, but it took me a while to figure out why I was crashing and I think others will make the same mistake.

**Comment by Thecarisma** [comment]
Hello MarcelInTO,

I have created the page
https://exoticlibraries.github.io/libcester/docs/known_issues.html to track
this type of issue and all that not possible in libcester, the page
includes an explanation on why automatic variable does not work in the test
fixture and how to get around them.
